[target.arm-unknown-linux-gnueabihf]
image = "phnz/tauri:arm-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
image = "phnz/tauri:armv7-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "phnz/tauri:aarch64-unknown-linux-gnu"
